### ISSUE TITLE
vg_api client tool features

### ISSUE THREAD

**Issue by davmlaw** [SACGF/vg_api#1]
* Return key/value fields from API instead of just ID
* Write out VCF file with fields
* query per gene
* query per dbsnp
* query per locus
* query per variant

**Comment by TheMadBug** [comment]
I think at this point it's safe to say people will be integrating with Shariant via export in an appropriate format (MVL, VCF, CSV) etc.
I don't believe queries through the api tool would be utilised.

At a later date when more instantaneous integration is required we can evaluate the best way to go forward.
